public with sharing class AppLiteralscls {
	public static boolean stopAccountAction=false;
	public static boolean stopOutboundcalls2ndtime=false;
	public static Set<String> campaignNamesSet 
								= new Set<String>{'New Member welcome message-Offline w/o email S-40',
													'New Member welcome message-Offline w/o email S-50',
													'New Member welcome message-Offline w/o email S-60',
													'New Member welcome message-Offline w/o email for ALL',
													'New Member welcome message - Offline with email S-40',
													'New Member welcome message - Offline with email S-50',
													'New Member welcome message - Offline with email S-60',
													'New Member welcome message - Offline with email for ALL',
													'New Member welcome message - Online with email S-40',
													'New Member welcome message - Online with email for ALL',
													'Birthday Greeting and Offer-Birthday-SMS-S-40',
													'Birthday Greeting and Offer-Birthday-SMS-S-50',
													'Birthday Greeting and Offer-Birthday-eDM-S-60',
													'Birthday Greeting and Offer-Birthday-eDM-S-40',
													'Birthday Greeting and Offer-Birthday-eDM-S-60',
													'Birthday Greeting and Offer-Transition-SMS-Turning 50',
													'Birthday Greeting and Offer-Transition-eDM-Turning 50',
													'Birthday Greeting and Offer-Transition-SMS-Turning 60',
													'Birthday Greeting and Offer-Transition-eDM-Turning 60',
													'Member Regular Communication S-40',
													'Member Regular Communication S-50',
													'First Purchase Offer-SMS-S-40',
													'First Purchase Offer-SMS-S-50',
													'First Purchase Offer-SMS-S-60',
													'First Purchase Offer-eDM-S-40',
													'First Purchase Offer-eDM-S-50',
													'First Purchase Offer-eDM-S-60'};
}