public with sharing class FCHK_Cls_MemberDetailParsercls {
		public class FCHK_Cls_MemberDetailcls{
            public String firstName{get;set;}
            public String lastName{get;set;}
            public String memberEmail{get;set;}
            public String memberPhone{get;set;}
           // public Date   memberDOB{get;set;}  
            public String birthDay{get;set;}
            public String birthMonth{get;set;}
            public String birthYear{get;set;}   
            public String password{get;set;}
            //public String userName{get;set;}
            public String recruitmentSource{get;set;}
            public String registrationType{get;set;}
            public String gender{get;set;}
            public String homePhone{get;set;}
            //Declaration of variables for For Interest fields 
            public boolean health{get;set;}
            public boolean familyActivities{get;set;}
            public boolean foodandNutrition{get;set;}
            public boolean travel{get;set;}
            public boolean entertainmentandLeisure{get;set;}
            public boolean shopping{get;set;}
            public boolean sportsandWellness{get;set;}
            public boolean retirementPlanning{get;set;}           
            //End of Declaration of variables for For Interest fields 
            public boolean agreeTerms{get;set;}
            //public String faceBookId{get;set;}
            public Date referredOn{get;set;}
            public String referredBy{get;set;}
            public String promotionCode{get;set;}
            
        }
}